SET IDENTITY_INSERT [dbo].[dataaa] ON
INSERT INTO [dbo].[dataaa] ([Id], [Login Date], [Email], [Name], [Age], [Bday], [Address]) VALUES (1, N'20/06/2022', N'jcdeguzman1218@gmail.com', N'John Carlo Barrientes De Guzman                                                                     ', 19, N'Dec. 18, 2002', N'Lapnit San Ildefonso Bulacan')
INSERT INTO [dbo].[dataaa] ([Id], [Login Date], [Email], [Name], [Age], [Bday], [Address]) VALUES (2, N'20/06/2022', N'jpubaldo19@gmail.com', N'John Paulo Ubaldo De Guzman                                                                         ', 19, N'Aug. 04, 2002', N'Lapnit San Ildefonso Bulacan')
INSERT INTO [dbo].[dataaa] ([Id], [Login Date], [Email], [Name], [Age], [Bday], [Address]) VALUES (3, N'21/06/2022', N'jkbarrientes@gmail.com', N'John Kurt Cruz Barrientes                                                                           ', 19, N'Oct. 12, 2002', N'Lapnit San Ildefonso Bulacan')
INSERT INTO [dbo].[dataaa] ([Id], [Login Date], [Email], [Name], [Age], [Bday], [Address]) VALUES (4, N'22/06/2022', N'joeydg@gmail.com', N'Joey Cruz De Guzman                                                                                 ', 20, N'Jan. 24, 2002', N'San Juan San Ildefonso Bulacan')
INSERT INTO [dbo].[dataaa] ([Id], [Login Date], [Email], [Name], [Age], [Bday], [Address]) VALUES (5, N'23/06/2022', N'jamesbarrientes@gmail.comm', N'James Liwag Barrientes                                                                              ', 20, N'March 24, 2002', N'Calawitan San Ildefonso Bulacan')
INSERT INTO [dbo].[dataaa] ([Id], [Login Date], [Email], [Name], [Age], [Bday], [Address]) VALUES (6, N'23/06/2022', N'pauldelacruz@gmail.com', N'Paul Liwag Dela Cruz                                                                                ', 19, N'Dec. 08, 2002', N'Malipampang San Ildefonso Bulacan')
INSERT INTO [dbo].[dataaa] ([Id], [Login Date], [Email], [Name], [Age], [Bday], [Address]) VALUES (7, N'24/06/2022', N'johnbarrientes@gmail.com', N'John Cruz Barrientes                                                                                ', 19, N'Nov. 18, 2002', N'San Juan San Ildefonso Bulacan')
SET IDENTITY_INSERT [dbo].[dataaa] OFF
